### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by BwamNL** [japaniot/homebridge-mitsubishi-aircon#3]
Hello!

I am running HomeBridge on a Synology. When I start I get the following error:

`[4/28/2020, 8:48:50 AM] Homebridge is running on port 52360.
(node:4478) UnhandledPromiseRejectionWarning: Error: Text data outside of root node.
Line: 0
Column: 392
Char: }
    at error (/homebridge/node_modules/homebridge-mitsubishi-aircon/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/homebridge/node_modules/homebridge-mitsubishi-aircon/node_modules/sax/lib/sax.js:677:7)
    at SAXParser.write (/homebridge/node_modules/homebridge-mitsubishi-aircon/node_modules/sax/lib/sax.js:1035:15)
    at module.exports (/homebridge/node_modules/homebridge-mitsubishi-aircon/node_modules/xml-js/lib/xml2js.js:346:12)
    at Object.deviceList (/homebridge/node_modules/homebridge-mitsubishi-aircon/lib/parse.js:4:15)
    at Object.loadAll (/homebridge/node_modules/homebridge-mitsubishi-aircon/lib/service.js:18:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at MitsubishiAircon._init (/homebridge/node_modules/homebridge-mitsubishi-aircon/lib/index.js:59:21)
(node:4478) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4478) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.,`

Not sure if I am doing anything wrong. Any help is appreciated!

**Comment by BwamNL** [comment]
I found out that this plugin is not for my airco, but this one is: https://github.com/Rickth64/homebridge-mhacwifi1#readme And it works!
