### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by morphix9** [japaniot/homebridge-mitsubishi-aircon#4]
(node:2406) UnhandledPromiseRejectionWarning: Error: Text data outside of root node.
Line: 0
Column: 392
Char: }
    at error (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/node_modules/sax/lib/sax.js:677:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/node_modules/sax/lib/sax.js:1035:15)
    at module.exports (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/node_modules/xml-js/lib/xml2js.js:346:12)
    at Object.deviceList (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/lib/parse.js:4:15)
    at Object.loadAll (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/lib/service.js:18:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at MitsubishiAircon._init (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/lib/index.js:60:21)
(node:2406) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2406) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by majchrzak-dev** [comment]
same here, nothing has been fixed since 19 Aug 2020?

(node:3114) UnhandledPromiseRejectionWarning: Error: Text data outside of root node.
Line: 0
Column: 392
Char: }
    at error (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/node_modules/sax/lib/sax.js:677:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/node_modules/sax/lib/sax.js:1035:15)
    at module.exports (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/node_modules/xml-js/lib/xml2js.js:346:12)
    at Object.deviceList (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/lib/parse.js:4:15)
    at Object.loadAll (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/lib/service.js:18:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at MitsubishiAircon._init (/usr/local/lib/node_modules/homebridge-mitsubishi-aircon/lib/index.js:60:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
